# Shipping Calculator API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookieshop-web
  labels:
    app: cookieshop
spec:
  selector:
    matchLabels:
      app: cookieshop
      role: web
  replicas: 1
  template:
    metadata:
      labels:
        app: cookieshop
        role: web
    spec:
      containers:
      - name: web
        # TODO: allow kustomize here
        image: gcr.io/gcb-demo/cookieshop/web:VERSION_TAG
        ports:
        - containerPort: 8080