apiVersion: v1
kind: Service
metadata:
  name: cookieshop-web
  labels:
    app: cookieshop
    role: web
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
  selector:
    role: web
    app: cookieshop