steps:
- name: node:12
  entrypoint: npm
  args: ['test']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/hello']
- name: gcr.io/cloud-builders/gcloud
  args: 
    [
      "beta","run","deploy","hello",
      "--image=gcr.io/$PROJECT_ID/hello",
      "--platform=managed",
      "--region=us-central1",
      "--allow-unauthenticated"
    ]