steps:

- name: node:12
  id: 'lint'
  entrypoint: npm
  args: ['run','lint']

- name: node:12
  id: 'test'
  entrypoint: npm
  args: ['test']

- name: gcr.io/cloud-builders/docker
  id: 'containerize'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']

- name: gcr.io/cloud-builders/docker
  id: 'push container'
  args: ['push','gcr.io/$PROJECT_ID/hello']

- name: gcr.io/cloud-builders/gcloud
  id: 'deploy'
  args: 
    [
      "beta","run","deploy","hello",
      "--image=gcr.io/$PROJECT_ID/hello",
      "--platform=managed",
      "--region=us-central1",
      "--allow-unauthenticated"
    ]